---
additionalVolumes:
  - emptyDir: {}
    name: nginx-run

additionalPodVolumeMounts:
  - mountPath: /var/cache/nginx
    name: nginx-run

probes:
  livenessProbe:
    httpGet:
      path: /
      port: 8080
    failureThreshold: 3
    periodSeconds: 5
  startupProbe:
    httpGet:
      path: /
      port: 8080
    failureThreshold: 12
    periodSeconds: 5
